[package]
name = "genpdf-json"
version = "0.1.12"
edition = "2024"
authors = [
    "Numael Garay <mantrixsoft@gmail.com>"
]
exclude = [".builds/*"]
keywords = ["json", "pdf", "text", "layout"]
homepage = "https://github.com/numaelis/genpdf-json-rs"
repository = "https://github.com/numaelis/genpdf-json-rs"
license = "GPL3"    

[dependencies]
#support json rckive-genpdf-rs -> https://github.com/numaelis/rckive-genpdf-rs.git
rckive-genpdf = {version = "0.4.3", git = "https://github.com/numaelis/rckive-genpdf-rs.git", features = ["images", "hyphenation"]}
#rckive-genpdf = {version = "0.4.3", path = "rckive-genpdf/", features = ["images", "hyphenation"]}
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = "0.29.0"
hyphenation = { version = "0.8", features = ["embed_en-us"] }
